trigger:
- master

stages:
  - stage: build
    displayName: 'master-branch-build'

    #build jobs
    jobs: 
      - job: build
        pool:
          name: 'plant-pool'

        variables:
          buildConfiguration: 'Release'

        steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: 'restore'
            projects: '/Plant/*.csproj'
            feedsToUse: 'select'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            projects: '/Plant/*.csproj'
            arguments: '--configuration $(BuildConfiguration)'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'publish'
            publishWebProjects: true
            arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(build.artifactstagingdirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
  - stage: release
    displayName: 'deployment-release'
#release job
    jobs:
      - job: release
        pool:
              name: 'plant-pool'
        steps:
        - task: DownloadBuildArtifacts@0
          inputs:
            buildType: 'current'
            downloadType: 'specific'
            itemPattern: '**/*.zip'
            downloadPath: '$(System.ArtifactsDirectory)'
        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'Avanade Delivery(3eba6e29-3983-495b-a539-c3c4b43fb90c)'
            appType: 'webAppLinux'
            WebAppName: 'katwebapp'
            packageForLinux: '$(System.DefaultWorkingDirectory)/'
            RuntimeStack: 'DOTNETCORE|5.0'
