// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Plant.Data;

namespace Plant.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Plant.Models.myGarden", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ID");

                    b.ToTable("Gardens");
                });

            modelBuilder.Entity("Plant.Models.myPlant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DateLastWatered")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DatePlanted")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("GardenID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ID");

                    b.HasIndex("GardenID");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("Plant.Models.myPlant", b =>
                {
                    b.HasOne("Plant.Models.myGarden", "Garden")
                        .WithMany()
                        .HasForeignKey("GardenID");

                    b.Navigation("Garden");
                });
#pragma warning restore 612, 618
        }
    }
}
